steps:
# Configura el proyecto de Google Cloud
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'desafio-tripulaciones-2']

# Construye la imagen del contenedor
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/desafio-tripulaciones-2/repodesafio-dev/server-dev:1.0', '-f', 'Dockerfile', '.']

# Sube la imagen del contenedor a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/desafio-tripulaciones-2/repodesafio-dev/server-dev:1.0']

# Despliega la imagen del contenedor en Cloud Run
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-server-dev
    --image=europe-west1-docker.pkg.dev/desafio-tripulaciones-2/repodesafio-dev/server-dev:1.0 
    --region=europe-west1 
    --platform=managed 
    --allow-unauthenticated 
    --port=5174
    --update-env-vars
      ULTRA_SECRET_KEY=$$ULTRA_SECRET_KEY,\
      DB_HOST=$$DB_HOST,\
      DB_USER=$$DB_USER,\
      DB_DATABASE=$$DB_DATABASE,\
      DB_PORT=$$DB_PORT,\
      DB_PASSWORD=$$DB_PASSWORD"
  ]

  secretEnv: [
    'ULTRA_SECRET_KEY',
    'DB_HOST',
    'DB_USER',
    'DB_DATABASE',
    'DB_PORT',
    'DB_PASSWORD'
  ]

images:
- 'europe-west1-docker.pkg.dev/desafio-tripulaciones-2/repodesafio-dev/server-dev:1.0'

availableSecrets:
  secretManager:
    - versionName: projects/214133582880/secrets/ULTRA_SECRET_KEY/versions/latest
      env: 'ULTRA_SECRET_KEY'
    - versionName: projects/214133582880/secrets/DB_HOST/versions/latest
      env: 'DB_HOST'
    - versionName: projects/214133582880/secrets/DB_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/214133582880/secrets/DB_DATABASE/versions/latest
      env: 'DB_DATABASE'
    - versionName: projects/214133582880/secrets/DB_PORT/versions/latest
      env: 'DB_PORT'
    - versionName: projects/214133582880/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'